name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@v14
        with:
          use-flakehub: false

      - name: Check flake
        run: nix flake check --all-systems -L

      - name: Build packages
        run: nix build -L .#cli .#applet .#full

      - name: Package build outputs
        run: |
          mkdir -p artifacts
          tar --dereference -C result -czf artifacts/battery-up-cli-x86_64-linux.tar.gz .
          tar --dereference -C result-1 -czf artifacts/battery-up-cosmic-applet-x86_64-linux.tar.gz .
          tar --dereference -C result-2 -czf artifacts/battery-up-full-x86_64-linux.tar.gz .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: battery-up-${{ github.sha }}
          path: artifacts/*.tar.gz
          if-no-files-found: error
